theme: jekyll-theme-minimal

title: Susanne Suvanto
description: Place for random technical adventures

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
